WEB_253505_Shishov/WEB_253505_Shishov/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WEB_253505_Shishov.Domain.Entities;
using WEB_253505_Shishov.Services.ConstructorService;

namespace WEB_253505_Shishov.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IConstructorService _constructorService;
        private readonly Cart _cart;
        public CartController(IConstructorService constructorService, Cart cart)
        {
            _constructorService = constructorService;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(_cart);
        }

		[Route("[controller]/add/{id:int}")]
		public async Task<IActionResult> AddItem(int id, string returnUrl)
        {
            var data = await _constructorService.GetProductByIdAsync(id);
            if (data.Successfull)
            {
                _cart.AddToCart(data.Data);
            }

            return Redirect(returnUrl);
        }

        [Route("[controller]/remove/{id:int}")]
        public async Task<IActionResult> RemoveItem(int id, string returnUrl)
        {
            var data = await _constructorService.GetProductByIdAsync(id);
            if (data.Successfull)
            {
                _cart.RemoveItems(id);
            }

            return Redirect(returnUrl);
        }
    }
}

WEB_253505_Shishov/WEB_253505_Shishov/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_253505_Shishov.Extensions;
using WEB_253505_Shishov.Services.CategoryService;
using WEB_253505_Shishov.Services.ConstructorService;

namespace WEB_253505_Shishov.Controllers
{
    [Route("Catalog")]
    public class ProductController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IConstructorService _constructorService;
        public ProductController(IConstructorService constructorService, ICategoryService categoryService)
        {
            _categoryService = categoryService;
            _constructorService = constructorService;
        }

        [HttpGet("{category?}")]
        public async Task<IActionResult> Index(string? category, int pageNo = 1)
        {
            var productResponse =
                await _constructorService.GetProductListAsync(category, pageNo);
            if (!productResponse.Successfull)
            {
                return NotFound(productResponse.ErrorMessage);
            }

            var allCategories =
                await _categoryService.GetCategoryListAsync();
            if (!allCategories.Successfull)
            {
                return NotFound(allCategories.ErrorMessage);
            }

			var currentCategory = category == null ? "Все" : allCategories.Data!.FirstOrDefault(c => c.NormalizedName == category)?.Name;

			ViewData["Categories"] = allCategories.Data;
            ViewData["CurrentCategory"] = currentCategory;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_PagerAndCardsPartial", new
                {
                    CurrentCategory = category,
                    Categories = allCategories.Data,
                    Products = productResponse.Data!.Items,
                    ReturnUrl = Request.Path + Request.QueryString.ToUriComponent(),
                    CurrentPage = productResponse.Data.CurrentPage,
                    TotalPages = productResponse.Data.TotalPages,
                    Admin = false
			    });
            }

			return View(productResponse.Data);
        }
    }
}

WEB_253505_Shishov/WEB_253505_Shishov/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-light">

               <partial name="_MenuPartial" />

               <partial name="_UserInfoPartial"/>

            </nav>
        </div>
    </header>
    <main class="container">
        @RenderBody()
    </main>
    <footer>
        <div class="container">
            <nav class="navbar navbar-expanded-md navbar-light bg-lights">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.instagram.com">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa-brands fa-vk"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.x.com">
                        <i class="fa-brands fa-x-twitter"></i>
                    </a>
                </div>
            </nav>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WEB_253505_Shishov/WEB_253505_Shishov/Views/Shared/_MenuPartial.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower() ?? string.Empty;
    var area = ViewContext.RouteData.Values["area"]?.ToString()?.ToLower() ?? string.Empty;
}

<a class="navbar-brand" href="#">Title</a>

<div class="navbar-nav">
    <a class="nav-item nav-link @(controller == "home" ? "active" : "")" asp-controller="Home" asp-action="Index">Lab1</a>
    <a class="nav-item nav-link @(controller == "product" ? "active" : "")" asp-controller="Product" asp-action="Index">Catalog</a>
    <a class="nav-item nav-link @(area == "Admin" ? "active" : "")" asp-area="Admin" asp-page="/Index">Administration</a>
</div>

WEB_253505_Shishov/WEB_253505_Shishov/Views/Shared/_PagerAndCardsPartial.cshtml
@{

}

@if (!Model.Admin)
{
	<div class="container mt-3" id="catalog">
		<div class="row offset-1" id="legoContainer">
			@foreach (var item in Model.Products)
			{
				<div class="com-sm-6 col-md-4 mb-4">
					<div class="card h-100">
						<div class="card-header text-center bg-white">
							<img src="@item.Image" class="card-img-top" style="max-width: 200px; height: 100%" />
						</div>
						<div class="card-body">
							<p class="card-title fs-3 fw-bold">@item.Description</p>
							<p class="card-text fs-5 fw-light">@item.Picies pcs</p>
							<p class="card-text fs-5 fw-light">Price: @item.Price $</p>
							<p class="card-text fs-5 fw-italic">@item.CategoryId</p>
						</div>
						@if (User.Identity.IsAuthenticated)
						{
							<div class="card-footer" style="text-align:center;">
								<a asp-controller="Cart"
								   asp-action="AddItem"
								   asp-route-id="@item.Id"
								   asp-route-returnurl="@Model.ReturnUrl"
								   class="btn btn-primary">
									Добавить в корзину
									<i class="fa-solid fa-cart-shopping"></i>
								</a>
							</div>
						}
					</div>
				</div>
			}
		</div>

		<pager current-page="@Model.CurrentPage"
			   total-pages="@Model.TotalPages"
			   category="@Model.CurrentCategory">
		</pager>

	</div>
}
else
{
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Description</th>
				<th scope="col">Price</th>
				<th scope="col">Picies</th>
				<th scope="col">Image</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Constructors)
			{
				<tr>
					<th scope="row">@item.Description</th>
					<td>@item.Price</td>
					<td>@item.Picies</td>
					<td><img src="@item.Image" style="max-width:150px;" /></td>
					<td>
						<a class="btn btn-primary" asp-area="Admin" asp-page="/Edit" asp-route-id="@item.Id">Edit</a>
						<a class="btn btn-primary" asp-area="Admin" asp-page="/Details" asp-route-id="@item.Id">Details</a>
						<a class="btn btn-primary" asp-area="Admin" asp-page="/Delete" asp-route-id="@item.Id">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	</table>

	<pager current-page="@Model.CurrentPage"
		   total-pages="@Model.TotalPages"
		   admin="true"></pager>
}

WEB_253505_Shishov/WEB_253505_Shishov/Views/Shared/_UserInfoPartial.cshtml
@{
    var name = User.Claims.FirstOrDefault(c => c.Type.Equals("preferred_username", StringComparison.OrdinalIgnoreCase))?.Value;

    var avatar = User
    .Claims
    .FirstOrDefault(c => c.Type.Equals("avatar", StringComparison.OrdinalIgnoreCase))?
    .Value ?? "images/default-profile-picture.png";
}

@if (User.Identity.IsAuthenticated)
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ms-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle"
                type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown"
                aria-expanded="false">
                @name
            <img src="@avatar" width="30"
                 alt="User" class="rounded nav-color" />
        </button>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">

            <li>
                <span class="dropdown-item-text">
                    <img src="images/default-profile-picture.png"
                         width="50" alt="User" class="rounded" />
                    @name
                </span>
            </li>

            <li><hr class="dropdown-divider"></li>

            <li>
                <form id="logoutForm" class="form-inline" asp-controller="Account" asp-action="Logout">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">
                        Logout
                    </button>
                </form>
            </li>

        </ul>

    </div>
}
else
{
    <div class="container nav-color">
        <div class="row ms-4">
            <div class="col-sm">
                <a class="nav-link btn btn-link text-dark" asp-controller="Account" asp-action="Login">
                    Login
                </a>
            </div>
            <div class="col-sm">
                <a class="nav-link btn btn-link text-dark" asp-controller="Account" asp-action="Register">
                    Register
                </a>
            </div>
        </div>
    </div>
}